---
language: go
go:
  - 1.11.x
install: true
services:
  - docker
before_script:
  - docker-compose up -d
  - .ci/install-vault.sh
  - .ci/bootstrap-vault.sh
  - make dep
script:
  - export VAULT_HANDLER_VAULT_ROLE_ID=$(grep ROLE_ID .env |awk -F '"' '{print $2}')
  - export VAULT_HANDLER_VAULT_SECRET_ID=$(grep SECRET_ID .env |awk -F '"' '{print $2}')
  - make bootstrap
  - make
  - make test
  # - make integration
after_success:
  - make codecov
