required = [
    "k8s.io/client-go/plugin/pkg/client/auth/gcp"
]

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

  [[prune.project]]
    name = "k8s.io/kubernetes"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/client-go"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/apimachinery"
    non-go = false
    unused-packages = false

  [[prune.project]]
    name = "k8s.io/api"
    non-go = false
    unused-packages = false

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "1.0.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.1"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[constraint]]
  name = "github.com/subosito/gotenv"
  version = "1.1.1"

[[constraint]]
  name = "gopkg.in/alessio/shellescape.v1"
  version = "1.2.0"

[[constraint]]
  branch = "fuzz"
  name = "github.com/mvdan/sh"

[[constraint]]
  name = "mvdan.cc/sh"
  version = "2.6.4"
